spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8093
